"""Structural chunking for datasheets.

Naive "split every 500 characters" destroys the value of a datasheet: the
Absolute Maximum Ratings table gets cut in half and the numbers lose their
headers. This module chunks by *meaning* instead:

  1. The markdown from the parser is split at every header. Each block becomes
     a section: General Description / Features / Pin Configuration /
     Absolute Maximum Ratings / Electrical Characteristics / Package Dimensions…
  2. Inside a section, tables stay whole — a ratings table is one chunk, never
     a fragment. This is what LlamaIndex's MarkdownElementNodeParser is for:
     it walks the markdown, recognises table elements and indexes them
     separately from prose.
  3. Every table gets a summary, so the *words* of the table are searchable
     even when the query does not match the exact cell text. With a real LLM
     configured the summary is generated by the model; offline we use a
     deterministic summariser (HeuristicLLM) that never needs the network.
  4. Every chunk is stamped with part number, manufacturer, section and page.
"""

from __future__ import annotations

import hashlib
import os
import re

# LlamaIndex prints tqdm progress bars from inside the element parser even with
# show_progress=False; in a batch pipeline that is pure noise.
os.environ.setdefault("TQDM_DISABLE", "1")
from dataclasses import dataclass, asdict, field
from typing import List, Optional, Tuple

# --------------------------------------------------------------------------- #
# Canonical sections
# --------------------------------------------------------------------------- #

SECTION_RULES: List[Tuple[str, str]] = [
    (r"absolute\s+maximum|maximum\s+ratings|limiting\s+values|stress\s+ratings", "absolute_maximum_ratings"),
    (r"recommended\s+operating|operating\s+conditions", "operating_conditions"),
    (r"electrical\s+characteristic|electrical\s+specification|dc\s+characteristic|ac\s+characteristic", "electrical_characteristics"),
    (r"pin\s*(configuration|assignment|description|out|function)|pinout|pin\s+layout|ball\s+map", "pin_configuration"),
    (r"package\s*(dimension|outline|drawing|information)|mechanical\s+(data|dimension)|footprint|land\s+pattern", "package_dimensions"),
    (r"thermal\s*(characteristic|resistance|data|information)|power\s+dissipation", "thermal"),
    (r"ordering\s*(information|code|guide)|part\s*number(ing)?\s*(scheme|information)?|marking\s*information", "ordering_information"),
    (r"\bfeatures?\b|key\s+benefits|characteristics\s+summary", "features"),
    (r"application|\buses?\b|typical\s+application", "applications"),
    (r"general\s+description|description|overview|introduction", "general_description"),
    (r"block\s+diagram|functional\s+diagram|schematic", "diagram"),
    (r"revision\s+history|document\s+history|table\s+of\s+contents|contents", "meta"),
]

SECTION_LABELS = {
    "absolute_maximum_ratings": "Absolute Maximum Ratings",
    "operating_conditions": "Operating Conditions",
    "electrical_characteristics": "Electrical Characteristics",
    "pin_configuration": "Pin Configuration",
    "package_dimensions": "Package Dimensions",
    "thermal": "Thermal Data",
    "ordering_information": "Ordering Information",
    "features": "Features",
    "applications": "Applications",
    "general_description": "General Description",
    "diagram": "Diagram",
    "meta": "Document Info",
    "other": "Other",
}


def classify_section(header: str) -> str:
    h = (header or "").lower()
    for pattern, name in SECTION_RULES:
        if re.search(pattern, h):
            return name
    return "other"


@dataclass
class Chunk:
    id: str = ""
    doc_id: str = ""
    part: Optional[str] = None
    manufacturer: Optional[str] = None
    package: Optional[str] = None
    section: str = "other"
    section_label: str = "Other"
    header: str = ""
    page: Optional[int] = None
    is_table: bool = False
    text: str = ""
    summary: str = ""
    order: int = 0

    def to_dict(self) -> dict:
        return asdict(self)


# --------------------------------------------------------------------------- #
# Deterministic table summariser (no network, no model)
# --------------------------------------------------------------------------- #

class HeuristicLLM:
    """Drop-in replacement for an LLM whose only job is table summaries.

    LlamaIndex's MarkdownElementNodeParser calls `Settings.llm` to summarise
    each table. In an offline environment (no OpenAI key, no local model,
    HuggingFace unreachable) that call is impossible. Rather than skip the
    parser, we plug in this class: it produces a deterministic, retrieval-
    friendly description of the table from the prompt text itself.

    It is NOT a language model and it is documented as such — swap it for a
    real LLM when one is available.

    Note: LlamaIndex validates `Settings.llm` with pydantic, so the concrete
    class handed to it must subclass `CustomLLM` — see `_build_heuristic_llm()`.
    """

    model_name = "heuristic-table-summariser"

    def _summary(self, text: str) -> str:
        return summarise_table_from_prompt(text)


def _build_heuristic_llm():
    """Subclass CustomLLM at runtime so it passes LlamaIndex's type checks."""
    from llama_index.core.llms import (
        CompletionResponse,
        CustomLLM,
        LLMMetadata,
    )

    class _HeuristicLLM(HeuristicLLM, CustomLLM):
        @property
        def metadata(self) -> LLMMetadata:
            return LLMMetadata(model_name=self.model_name, is_chat_model=False)

        def complete(self, prompt: str, formatted: bool = False, **kwargs):
            return CompletionResponse(text=self._summary(prompt))

        def stream_complete(self, prompt: str, formatted: bool = False, **kwargs):
            text = self._summary(prompt)

            def gen():
                yield CompletionResponse(text=text, delta=text)

            return gen()

        def chat(self, messages, **kwargs):
            text = "\n".join(getattr(m, "content", str(m)) for m in messages)
            return CompletionResponse(text=self._summary(text))

    return _HeuristicLLM()


def summarise_table_from_prompt(prompt: str, max_rows: int = 6) -> str:
    rows = [ln.strip() for ln in prompt.splitlines() if ln.strip().startswith("|")]
    rows = [r for r in rows if not re.match(r"^\|[\s\-|:]+\|$", r)]
    if not rows:
        return "Table fragment."

    def cells(r: str) -> List[str]:
        return [c.strip() for c in r.strip("|").split("|")]

    header = cells(rows[0])
    body = [cells(r) for r in rows[1:]]
    if len(rows) == 1:
        body = []

    parts: List[str] = []
    parts.append("Table with %d rows and %d columns." % (len(body), len(header)))
    if header and any(header):
        parts.append("Columns: %s." % ", ".join(h for h in header if h))
    for row in body[:max_rows]:
        values = [c for c in row if c]
        if values:
            parts.append(" - " + "; ".join(values[:6]))
    if len(body) > max_rows:
        parts.append(" - and %d more rows." % (len(body) - max_rows))
    return " ".join(parts)


# --------------------------------------------------------------------------- #
# element parsing
# --------------------------------------------------------------------------- #

class ElementSplitter:
    """Wraps LlamaIndex MarkdownElementNodeParser with a no-LLM fallback."""

    def __init__(self, use_llamaindex: bool = True, verbose: bool = False):
        self.backend = "llamaindex"
        self._parser = None
        self._error = ""
        if use_llamaindex:
            try:
                from llama_index.core import Settings
                from llama_index.core.node_parser import MarkdownElementNodeParser

                Settings.llm = _build_heuristic_llm()
                self._parser = MarkdownElementNodeParser(llm=Settings.llm, num_workers=1)
            except Exception as exc:  # noqa: BLE001
                self._parser = None
                self._error = "%s: %s" % (type(exc).__name__, exc)
        if self._parser is None:
            self.backend = "heuristic"

    def split(self, markdown: str) -> List[Tuple[str, bool]]:
        """Return a list of (text, is_table) elements."""
        if self._parser is None:
            return _heuristic_split(markdown)
        try:
            from llama_index.core.schema import Document

            nodes = self._parser.get_nodes_from_documents(
                [Document(text=markdown)], show_progress=False
            )
        except Exception:
            return _heuristic_split(markdown)

        elements: List[Tuple[str, bool]] = []
        for node in nodes:
            text = (node.text or "").strip()
            if not text:
                continue
            # LlamaIndex prefixes table nodes with its own caption line
            is_summary = text.lower().startswith("table, with the following columns")
            is_table = _looks_like_table(text)
            if is_summary and not is_table:
                continue  # the summary is regenerated from the table itself
            if is_table:
                text = _strip_table_caption(text)
            elements.append((text, is_table))
        return elements or _heuristic_split(markdown)


def _looks_like_table(text: str) -> bool:
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    pipe_rows = [ln for ln in lines if ln.startswith("|") and ln.count("|") >= 2]
    return len(pipe_rows) >= 2


def _strip_table_caption(text: str) -> str:
    lines = text.splitlines()
    while lines and lines[0].strip().lower().startswith("table, with the following columns"):
        lines.pop(0)
    return "\n".join(lines).strip()


def _heuristic_split(markdown: str) -> List[Tuple[str, bool]]:
    """Fallback splitter: keeps pipe blocks together, splits prose by blank line."""
    blocks = re.split(r"\n\s*\n", markdown)
    elements: List[Tuple[str, bool]] = []
    for block in blocks:
        block = block.strip()
        if not block:
            continue
        elements.append((block, _looks_like_table(block)))
    return elements


# --------------------------------------------------------------------------- #
# document -> chunks
# --------------------------------------------------------------------------- #

HEADER_RE = re.compile(r"^(#{1,6})\s+(.*)$", re.MULTILINE)
PAGE_COMMENT_RE = re.compile(r"<!--\s*page\s+(\d+)\s*-->")


def split_blocks(markdown: str) -> List[Tuple[str, str]]:
    """Split markdown into (header, body) blocks. Text before the first header
    becomes the ('', body) block."""
    blocks: List[Tuple[str, str]] = []
    matches = list(HEADER_RE.finditer(markdown))
    if not matches:
        return [("", markdown)]

    pre = markdown[: matches[0].start()].strip()
    if pre:
        blocks.append(("", pre))
    for i, m in enumerate(matches):
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(markdown)
        body = markdown[start:end].strip()
        header = m.group(2).strip()
        blocks.append((header, body))
    return blocks


def _guess_page(text: str, pages) -> Optional[int]:
    """Map a chunk back to the page it came from by matching a distinctive
    fragment of the text against the page texts."""
    probe = " ".join(text.split())[:60]
    if len(probe) < 12:
        return None
    for page in pages:
        if probe and probe in " ".join(page.text.split()):
            return page.number
    # second chance: first table row or first long word
    m = re.search(r"[A-Za-z]{6,}", probe)
    if m:
        token = m.group(0)
        for page in pages:
            if token in page.text:
                return page.number
    return None


def chunk_document(
    parsed,
    meta,
    splitter: Optional[ElementSplitter] = None,
    max_chars: int = 1800,
) -> List[Chunk]:
    splitter = splitter or ElementSplitter()
    chunks: List[Chunk] = []
    order = 0

    for header, body in split_blocks(parsed.markdown):
        if not body.strip():
            continue
        section = classify_section(header)
        for text, is_table in splitter.split(body):
            text = text.strip()
            if not text or len(text) < 2:
                continue
            for piece in _maybe_split_long(text, max_chars, is_table):
                order += 1
                cid = hashlib.sha1(
                    ("%s|%s|%d" % (parsed.doc_id, header, order)).encode()
                ).hexdigest()[:16]
                summary = summarise_table_from_prompt(piece) if is_table else ""
                chunks.append(
                    Chunk(
                        id=cid,
                        doc_id=parsed.doc_id,
                        part=meta.part,
                        manufacturer=meta.manufacturer,
                        package=meta.package,
                        section=section,
                        section_label=SECTION_LABELS.get(section, "Other"),
                        header=header,
                        page=_guess_page(piece, parsed.pages),
                        is_table=is_table,
                        text=piece,
                        summary=summary,
                        order=order,
                    )
                )
    return chunks


def _maybe_split_long(text: str, max_chars: int, is_table: bool):
    """Tables are never split (a rating separated from its header is useless).
    Long prose is split on paragraph/sentence boundaries."""
    if len(text) <= max_chars or is_table:
        return [text]
    pieces, current = [], ""
    for para in re.split(r"\n\s*\n", text):
        if len(current) + len(para) + 2 > max_chars and current:
            pieces.append(current.strip())
            current = para
        else:
            current = (current + "\n\n" + para).strip()
    if current:
        pieces.append(current.strip())
    return [p for p in pieces if p]
